base:
  project: multi-disease-predictor
  random_state: 20
  split_ratio: 0.25

data_source:
  Anemia: data/processed/Anemia.csv
  Cardiovascular: data/processed/Cardiovascular.csv
  Heart: data/processed/cleaned_heart.csv
  Hepatitis_C: data/processed/Hepatitis_C.csv
  Lung_cancer: data/processed/lung_cancer_processed.csv
  Thyroid: data/processed/thyroid_cleaned_data.csv
  Stroke: data/processed/processed_healthcare_data.csv
  Liver: data/processed/indian_liver_patient_processed.csv  

Hepatitis_C:
  SVC:
    params:
      C: 10
      gamma: scale
      kernel: rbf
  model_path: models/hepatitis.joblib

Liver:
  RandomForestClassifier:
    params:
      n_estimators: 5
      min_sample_split: 2
  model_path: models/liver.joblib


Cardiovascular:
  RandomForestClassifier :
    params:
      max_depth: 10
      min_samples_leaf: 2
      min_samples_split: 2
      n_estimators: 100
  model_path: models/cardiovascular.joblib

Anemia:
  RandomForestClassifier :
    params:
      max_depth: 10
      min_samples_leaf: 2
      min_samples_split: 2
      n_estimators: 100
  model_path: models/anemia.joblib
  mlflow_config:
    artifacts_dir: artifacts
    experiment_name: Anemia
    run_name: anemia
    registered_model_name: RandomForestClassifier
    remote_server_uri: http://127.0.0.1:5000

lung_cancer:
  LogisticRegression :
    params:
      C: 0.1
      max_iter: 100
      penalty: l2
      solver: liblinear
  model_path: models/lung_cancer.joblib
  mlflow_config:
    artifacts_dir: artifacts
    experiment_name: Lung_cancer
    run_name: lung_cancer
    registered_model_name: LogisticRegression
    remote_server_uri: http://127.0.0.1:5000



mlflow_config:
  artifacts_dir: artifacts
  experiment_name: hepatitis
  run_name: liver
  registered_model_name: RandomForestClassifier
  remote_server_uri: http://127.0.0.1:5000
