channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=23.2.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - numpy==2.2.4
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
