channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==2.21.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==7.0.0
  - scikit-learn==1.3.0
  - scipy==1.15.2
name: mlflow-env
